send_metrics = false

name = "web-builder"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[env.production]
workers_dev = false
route = "builder.inja.online/*"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
